version: "3.7"
services:
  django:
    container_name: testing-django
    build: .
    image: django-server

    # Allows me to run an interactive shell to interact with my server
    # These lines of code let us run an interactive terminal when running the 'Docker-compose up' command
    # ===============
    stdin_open: true
    tty: true
    # ===============

    volumes:
      - .:/var/www/myproject
    ports:
      - "8000:8000"