# version: "3.7"
# services:
#     web:
#         build: .
#         ports:
#             - "8000:80"
#         depends_on:
#             - db
#     db:
#         image: "mcr.microsoft.com/mssql/server"
#         environment:
#             SA_PASSWORD: "Testing1234"
#             ACCEPT_EULA: "Y"

version: "3.7"
services:
  django:
    container_name: testing-django
    build:
      context: .
      dockerfile: Dockerfile
    image: django-server

    # Allows me to run an interactive shell to interact with my server
    # ===============
    stdin_open: true
    tty: true
    # ===============

    volumes:
      - .:/var/www/myproject
    ports:
      - "8000:8000"